//course
export const SET_COURSE_ITEM = 'SET_COURSE_ITEM'
//lesson
export const SET_LESSON_ITEM = 'SET_LESSON_ITEM'
//session
export const SET_SESSION_ITEM = 'SET_SESSION_ITEM'
//material
export const SET_MATERIAL_ITEM = 'SET_MATERIAL_ITEM'
//assignment
export const SET_ASSIGNMENT_ITEM = 'SET_ASSIGNMENT_ITEM'
//quizz
export const SET_QUIZZ_ITEM = 'SET_QUIZZ_ITEM'
export const GET_QUIZZ_QUESTIONS = 'GET_QUIZZ_QUESTIONS'
export const SHOW_QUIZZ_QUESTION_MODAL = 'SHOW_QUIZZ_QUESTION_MODAL'
//user
export const RECEIVE_ACCESS_TOKEN = 'RECEIVE_ACCESS_TOKEN';
export const RECEIVE_USER_ACCOUNT = 'RECEIVE_USER_ACCOUNT';
export const LOGOUT = 'LOGOUT';
